repos:
  - repo: local
    hooks:
      - id: install-package
        name: Install Package in Editable Mode
        entry: pipenv install -e .
        language: system
        pass_filenames: false
        always_run: true
      - id: run-tests
        name: Run Unit Tests
        entry: pipenv run python test/populate_test/run_tests.py
        language: system
        pass_filenames: false
        always_run: true