# This workflow will check formatting with Black, install Python dependencies, and run tests with pytest
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# Apply this workflow when creating a pull request or pushing a commit to a PR
on: pull_request

jobs:
  black-formatting-check:
    name: Black formatting check
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - uses: psf/black@stable
        with:
          version: "24.2.0"
#  run-unit-tests:
#    name: Run unit tests
#    runs-on: 'ubuntu-latest'
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#          cache: 'pipenv'
#      - name: Install pipenv
#        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
#      - name: Install dependencies
#        run: pipenv install --dev
#      - name: Run pytests
#        # This will halt the action if any of the tests fail
#        run: pipenv run pytest -v
  rpd-validation-test:
    name: Run RPD validation tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
     - name: Checkout code
       uses: actions/checkout@v2

      # Step 2: Set up Python environment
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.8'

      # Step 3: Install pipenv and project dependencies
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pipenv
         pipenv install --dev

      # Step 4: Run the JSON comparison script using pipenv
#     - name: Run JSON comparison
#       run: |
#         pipenv run python compare_json.py path/to/reference.json path/to/generated.json path/to/tolerance.json
